
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/paymentdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true

  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296