server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/orderdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true

  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-37862078.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oab1wcoq3g9PmnCH5d7
            client-secret: o-czRLgG4NNbaqyGRwlotdMAlQ0EU9_J6csAXjt-sZARW_VyScZM-L8CDNsAiEyJ
        provider:
            okta:
                issuer-uri: https://dev-37862078.okta.com/oauth2/default



resilience4j:
  circuitbreaker:
    instances:
      external:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
