version: '3.7'

services:
  #service 1: definition of mongo database
  mongo_db:
    image: mongo
    container_name: mongoDB
    restart: always
    ports:
      - 27017:27017

    #service 2: definition of mongo-express


  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres